package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"io"
	"os"
	"path/filepath"
	"strconv"
)

func main() {
	var (
		inputPath  = flag.String("input", "", "path to the source skill markdown")
		outputPath = flag.String("output", "", "path to the generated Go file")
		varName    = flag.String("var", "", "generated string variable name")
	)

	flag.Parse()

	if *inputPath == "" || *outputPath == "" || *varName == "" {
		writeString(os.Stderr, "usage: generate_skill --input <path> --output <path> --var <name>\n")
		os.Exit(2)
	}

	content, err := os.ReadFile(*inputPath)
	if err != nil {
		writeFormat(os.Stderr, "read input: %v\n", err)
		os.Exit(1)
	}

	var buf bytes.Buffer
	writeFormat(&buf, "// Code generated by scripts/generate_skill.go from %s; DO NOT EDIT.\n", filepath.ToSlash(*inputPath))
	writeString(&buf, "package skill\n")
	writeString(&buf, "\n")
	writeFormat(&buf, "const %s = %s\n", *varName, strconv.Quote(string(content)))

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		writeFormat(os.Stderr, "format generated code: %v\n", err)
		os.Exit(1)
	}

	err = os.WriteFile(*outputPath, formatted, 0o644)
	if err != nil {
		writeFormat(os.Stderr, "write output: %v\n", err)
		os.Exit(1)
	}
}

func writeString(w io.Writer, text string) {
	_, err := io.WriteString(w, text)
	if err != nil {
		return
	}
}

func writeFormat(w io.Writer, format string, args ...any) {
	_, err := fmt.Fprintf(w, format, args...)
	if err != nil {
		return
	}
}
