package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strconv"
)

func main() {
	var (
		inputPath  = flag.String("input", "", "path to the source skill markdown")
		outputPath = flag.String("output", "", "path to the generated Go file")
		varName    = flag.String("var", "", "generated string variable name")
	)

	flag.Parse()

	if *inputPath == "" || *outputPath == "" || *varName == "" {
		fmt.Fprintln(os.Stderr, "usage: generate_skill --input <path> --output <path> --var <name>")
		os.Exit(2)
	}

	content, err := os.ReadFile(*inputPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read input: %v\n", err)
		os.Exit(1)
	}

	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Code generated by scripts/generate_skill.go from %s; DO NOT EDIT.\n", filepath.ToSlash(*inputPath))
	fmt.Fprintln(&buf, "package skill")
	fmt.Fprintln(&buf)
	fmt.Fprintf(&buf, "const %s = %s\n", *varName, strconv.Quote(string(content)))

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Fprintf(os.Stderr, "format generated code: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(*outputPath, formatted, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write output: %v\n", err)
		os.Exit(1)
	}
}
